<Project>
  <PropertyGroup>
    <AvaloniaVersion>12.1.2</AvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Headless.XUnit" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Silk.NET.OpenAL" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.OpenAL.Soft.Native" Version="1.23.1" />
    <PackageVersion Include="NVorbis" Version="0.10.5" />
    <PackageVersion Include="NLayer" Version="1.16.0" />
    <PackageVersion Include="Silk.NET.SDL" Version="2.23.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
